### ISSUE TITLE
Add option to continue to log errors

### ISSUE THREAD

**Issue by BobCashStory** [AndiDittrich/HttpErrorPages#19]
It should be great to continue to have console logger of error in the stdout as options

**Comment by AndiDittrich** [comment]
can you specify your feature request ?

**Comment by KenEucker** [comment]
@AndiDittrich I'm just guessing here, as I am new to working with HttpErrorPages, but @BobCashStory might be referring to the fact that errors get swallowed and are no longer printed to the console. Previously to integrating HttpErrorPages, when a request threw an error I was able to see that error. This might also be that I am not handling rejected promises correctly.

**Comment by AndiDittrich** [comment]
please specify to which kind of feature you're referring (static generator/expressjs/koajs/...)

**Comment by KenEucker** [comment]
@AndiDittrich I am using this package with expressjs.

**Comment by AndiDittrich** [comment]
could you provide a minimal example showing the current and expected behaviour ? which expressjs version ?

**Comment by KenEucker** [comment]
@AndiDittrich 
<img width="1633" alt="Screen Shot 2020-11-12 at 1 33 55 AM" src="https://user-images.githubusercontent.com/1720267/98922558-72caa480-2487-11eb-9610-cc879d4c1887.png">

I created a fork where I simply commented out the bootstrapping of the middleware. When you go to the /500 route you can see the error both in the node console and in the browser.

Fork: 
https://github.com/KenEucker/HttpErrorPages/tree/%2319-noMoreConsoleErrors

When errors like this are swallowed by this middleware, it can be hard to debug the cause of the issue. I may simply disable the use of HttpErrorPages when debugging in the meantime while I continue to ignore the uncaught promise rejections. :/

This is what you see, alternatively, when running the HttpErrorPages middleware:
<img width="1462" alt="Screen Shot 2020-11-12 at 1 42 01 AM" src="https://user-images.githubusercontent.com/1720267/98923298-55e2a100-2488-11eb-8a75-a5a73be42f4a.png">

**Comment by KenEucker** [comment]
@AndiDittrich Sorry to barrage you with comments on this.

The reason that I would find such a feature useful is that I am trying to track and address certain errors on my site pertaining to bot crawlers. For example, I want to keep track of the 404 and 302 requests that come to the server and having the option to pass a log handler to this middleware would be an elegant way for me to do that.

This would also allow people to pass stdout right on through and retain the error logging (in at least the console) you see above, which I outlined above.

**Comment by AndiDittrich** [comment]
i would say "you're doing it wrong" - normally you create your own errorhandling middleware, forward the request and just call HttErrorPages in the end to "display" the error

**Comment by KenEucker** [comment]
@AndiDittrich I disagree with you.

@BobCashStory if the solution I outlined is what you're looking for you can check out the changes I've made to my forked version of this package. https://github.com/keneucker/HttpErrorPages

Simply pass the option "logger" along with the other options, like so:
```
await _httpErrorPages.express(_webapp, {
        logger: console.error,
        lang: 'en_US',
        footer: 'Hello <strong>World</strong>'
    });
```
And you will see all errors logged to the console.

Note: I only added this functionality to the express version of this package. For the time being, that's all the investment I have available for this.

**Comment by AndiDittrich** [comment]
you know about expressjs `next()` callback ? it's intended for this kind of usage

**Comment by KenEucker** [comment]
@AndiDittrich yes, of course. I understand that an app can organize it's handlers as such:

```
app.use(logErrors)
app.use(clientErrorHandler)
app.use(errorHandler)
app.use(HttpErrorPages)
```

**Comment by AndiDittrich** [comment]
great, that's the intended control-flow of expressjs

**Comment by BobCashStory** [comment]
@AndiDittrich could you document it ? 
i just followed your exemple in the doc, with it that possible to do it ...
And goind in your code to understand what is going on, echo to "you're doing it wrong" to me ...

**Comment by AndiDittrich** [comment]
@BobCashStory 

for debugging purpose, you can use the new `onError` callback - but it's not designed to be used in produciton
https://github.com/HttpErrorPages/HttpErrorPages/blob/master/examples/express.js

**Comment by AndiDittrich** [comment]
@BobCashStory 

here you can find an example how you should handle error in production (you're just forwarding the exception to HttpErrorPages)
https://github.com/HttpErrorPages/HttpErrorPages/blob/master/examples/express.js#L34

**Comment by KenEucker** [comment]
@AndiDittrich Thank you for adding this to the latest update.

**Comment by AndiDittrich** [comment]
no problem, v3 was in a very early stage for month...therefore i had to finish that first.

**Comment by BobCashStory** [comment]
@AndiDittrich i tried like this :
```
const logErrors = (err, req, res, next) => {
    // eslint-disable-next-line no-console
    console.error(err.stack);
    next(err);
};
app.use(logErrors);
httpErrorPages.express(app, {
    lang: 'en_US',
});
```
and i still get no errors
<img width="526" alt="Screenshot 2020-11-19 at 10 48 50" src="https://user-images.githubusercontent.com/47117399/99656472-32f25700-2a5d-11eb-997f-726a579e5d82.png">

**Comment by AndiDittrich** [comment]
please try to example file mentioned above
