### ISSUE TITLE
Add option to pass additional parameters to the template

### ISSUE THREAD

**Issue by KenEucker** [AndiDittrich/HttpErrorPages#20]
It would be nice to have an option to add a method that wraps the data passed to the page-renderer, providing the req. Something to the effect of:

```
const errorDataHandler = (data, req) => {
    data.body = req.body
    data.redirectTo = req.host
}
 await httpErrorPages.express(this.app, {
            errorDataHandler,
            lang: 'en_US',
            footer: `hello <strong>world</strong>`,
        })
```

I can include changes to express.js to demonstrate how I think this could work and provide that in a PR to be examined alongside this issue.

**Comment by KenEucker** [comment]
~I implemented this on my fork:~
~https://github.com/KenEucker/HttpErrorPages/commit/21b9a2c65a46170c95f0f845ab6de953af05a8b2~

~In this example, if the field redirectTo is present a link is available on the error page to go back to the root URL.~

~Let me know if you find this useful.~

I did not see that this was implemented and proposed in another PR. 👍

**Comment by AndiDittrich** [comment]
the `req` and `ctx` variables can be exposed to the `filter` callback of v3

**Comment by KenEucker** [comment]
@AndiDittrich I'm updating to v3 now and things are going well. I have a question:

How do I expose the req variable in the filter callback?

**Comment by AndiDittrich** [comment]
https://github.com/HttpErrorPages/HttpErrorPages/commit/402f73502c774cfc4b6c5f618e41273a5a3a4157

**Comment by KenEucker** [comment]
@AndiDittrich Awesome, thank you so much, v3 is great! 🎉 👏 🎉
