### ISSUE TITLE
Add support for using res.locals in template file

### ISSUE THREAD

**Issue by KenEucker** [AndiDittrich/HttpErrorPages#21]
Thanks again for this package, @AndiDittrich.

I am currently working my way through CSP errors on all of my page templates and the last stop is the http-error-pages template. To overcome the CSP limitations with inline resources, I need to be able to insert a nonce where scripts and styles are inlined. In res.locals, at the beginning of each request, I create and assign the nonce value. If I had access to the response object in the opt.filter method, for example, I could add the nonce value there to be used in the template.

Alternatively, if I could set my own render method, I have my own ejs (and other) renderer(s) that ensure nonces are present on the correct tags. I am going to fork this repo once again and I can create a PR if/when I have something to present.

**Comment by AndiDittrich** [comment]
no problem: https://github.com/HttpErrorPages/HttpErrorPages/commit/e7ba75e59ecbb097db7fe92450d57d4695a5b4e2

**Comment by KenEucker** [comment]
@AndiDittrich you're a legend.
