### ISSUE TITLE
Start a crowdsourcing translate project maybe? 

### ISSUE THREAD

**Issue by boris1993** [AndiDittrich/HttpErrorPages#9]
Would you consider starting a crowdsourcing translation project on such platforms like Transifex or Conyac? 
People from all over the world can contribute their translation and make corrections on others'. 
Also, you can get the most accurate translation into different languages.

**Comment by AndiDittrich** [comment]
Hi @boris1993 

thanks for your suggestion! it's generally a geat idea but i didn't have the time to manage such campaign :(

**Comment by olokos** [comment]
apart from setting it up so that people could contribute there's not much to manage, once it's there - people just do the translations, really recommend it

**Comment by AndiDittrich** [comment]
any suggestions ? generally it's required that the "service" provides some kind of multiuser text validation...

**Comment by olokos** [comment]
Transifex is really good, you can assign trusted users to review the translations :)
